### PR TITLE
[WIP] feat: nftmarket v2 impl

### PR DESCRIPTION
**Pull request by Senna46**

### CODE REVIEW

**Comment by Senna46** [comment]
Current changes are not compatible with #15 and cannot be merged into `main`

**Comment by Senna46** [comment]
spec.ts
It can create new MsgPlaceBid
```
MsgPlaceBid {
      sender: 'cosmos14ynfqqa6j5k3kcqm2ymf3l66d9x07ysxgnvdyx',
      nft_id: NftIdentifier { class_id: 'a01', nft_id: 'a10' },
      bid_amount: Coin { denom: 'token', amount: '3' },
      bidding_period: Timestamp {
        seconds: Long { low: 1671107666, high: 0, unsigned: false },
        nanos: 534000000
      },
      deposit_lending_rate: '0.9',
      automatic_payment: true,
      deposit_amount: Coin { denom: 'token', amount: '1' }
    }
```
But, In Bubble, not properly (some field is deleted)
スクリーンショット 2022-12-15 150017

**Comment by Senna46** [comment]
Solved.
It is bacause of cdn conflict.

**Review by KimuraYu45z — APPROVED** [review]

**Comment by Senna46** [comment]
Once merged into derivatives branch for work

**Pull request merged**
