### PR TITLE
feat: apply cosmos-clientv0.45.1

### PR DESCRIPTION
**Pull request by taikiFurusyo**
・Applied to cosmos-client v0.45.1

### CODE REVIEW

**Comment by taikiFurusyo** [comment]
dependenciesにもcosmos-client/coreを追加しましたが（Build通すために）、するべきでなかったら教えてください。

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@taikiFurusyo 

Plz check following points.

1. You need to fix `"version": "0.44.3"` in `package.json` to `"version": "0.45.1"` and `npm i`.
2. I guess you can't execute `npm run gen:openapi` and `npm run gen:proto` correctly. To execute them correctly, you will need docker and UnUniFi/chain repository in your local machine's correct path. (It should be cloned to `~/src/github.com/UnUniFi/chain` and the repository should be checked out as the latest develop branch's state.)

**Comment by taikiFurusyo** [comment]
I didn't set the branch correctly.
Thank you for advise, I will try tomorrow.

**Comment by KimuraYu45z** [comment]
Sorry for late reply
I think you should input it into peerDependencies instead of dependencies.

https://github.com/cosmos-client/ibc-ts/blob/main/package.json#L54

There must be precedents so please try to refer them at first instead of reinventing the wheel.

**Comment by taikiFurusyo** [comment]
I had mistakenly set cosmos-client in dependencies and peerDependencies. 
I reset it to devDependencies and peerDependencies and the versions of other packages, following ibc-ts.

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Comment by KimuraYu45z** [comment]
However I don't have a conviction that I should input axios or other packages like bip32 into peerDependencies or not.
Please optimize it with researching when you have time

**Comment by taikiFurusyo** [comment]
I got it.
Thank you for the advise.

**Comment by KimuraYu45z** [comment]
I know that there is only cosmos client core in peerDependencies.
What I want to say is please consider to add other packages like axios into peerDependencies instead of dependencies if it is rational.

**Pull request merged**
